pipeline {
    agent any

    stages {
        stage('Build & Integration Test') {
            steps {
                sh 'mvn clean verify'
            }
        }
    }

    post {
        always {
            publishHTML([
                reportDir: 'integration-test/target/site',
                reportFiles: 'surefire-report.html, failsafe-report.html',
                reportName: 'Integration Test Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: false
            ])
        }
        failure {
            echo '❌ Some integration tests failed. See HTML report.'
        }
    }
}
