pipeline {
    agent any

    options { timestamps() }

    stages {
        stage('Build & Integration Test') {
            steps {
                dir('root-project') {
                    sh 'mvn -B clean verify'
                }
            }
        }
    }

    post {
        always {
            publishHTML([
                reportDir: 'root-project/integration-test/target/site',
                reportFiles: 'surefire-report.html, failsafe-report.html',
                reportName: 'Integration Test Report',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: true
            ])
        }
        failure {
            echo '❌ Some integration tests failed. See HTML report.'
        }
    }
}
